### ISSUE TITLE
Cloudflare config changed?

### ISSUE THREAD

**Issue by danhawkes** [nuxt/hackernews#11]
Hi, just wondering if the cloudflare config has been changed recently? 

I ask because I routinely browse over Tor and am suddenly faced with cloudflare's 'attention required!' page:

![cloudflare](https://user-images.githubusercontent.com/3388897/37957429-cf8333e0-31a5-11e8-893b-b1faba2616b2.png)

**Comment by pi0** [comment]
Hi. Yes for improving TTI we use Cloudflare's CDN proxy. How often this captcha requirement happens?

**Comment by danhawkes** [comment]
Every page load, and as of late it's not even bypassable via the captcha:

![screenshot from 2018-03-27 10-28-12](https://user-images.githubusercontent.com/3388897/37958912-abac4142-31a9-11e8-8f88-909ab66952c2.png)

Could you please consider whitelisting Tor traffic via one of the methods described here?

<https://support.cloudflare.com/hc/en-us/articles/203306930-Does-CloudFlare-block-Tor->

**Comment by Atinux** [comment]
I changed the security check to low inside CloudFlare, this should fix this issue.

**Comment by danhawkes** [comment]
Still doesn't work, I'm afraid. Could you please try whitelisting the Tor 'country' as described in the firewall section?

**Comment by Atinux** [comment]
I added it @danhawkes, can you confirm it's working?

**Comment by danhawkes** [comment]
Yes, it is! Thanks very much for your help.
